server:
  port: 8080
spring:
  application:
    name: cloud-order-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud?chararcterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
# 别名：
  type-aliases-package: cn.edw.springcloud.domain.po
  configuration:
    map-underscore-to-camel-case: true
eureka:
  client:
    # 向注册中心注册自己
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认true。
    # 单节点无所谓，集群必须设计为true才能配置Ribbon负载均衡
    fetch-registry: true
    # 与Eureka Server交互的服务都需要这个地址
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka,http://eureka8002.com:8002/eureka

